name: matriksapk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Tambahkan ini untuk mengubah icon aplikasi
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: "^1.1.0"


# Konfigurasi Icon Aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/matrix.png"  # <-- Ganti jadi matrix.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Konfigurasi assets
  assets:
    - assets/matrix.png            # <-- Ganti jadi matrix.png